// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID       int32
	Name     string
	Email    string
	Avatar   pgtype.Text
	Password string
}
