// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package database

import (
	"context"
)

const getAccountByName = `-- name: LoginByNameAndPassword :one
SELECT id, name, email, avatar, password
FROM account
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.Password,
	)
	return i, err
}
