// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	GetAccountByName(ctx context.Context, name string) (Account, error)
}

var _ Querier = (*Queries)(nil)
